### ISSUE TITLE
AttributeError: 'VNet' object has no attribute 'contrastive_class_selector_2'

### ISSUE THREAD

**Issue by hkxxxxx** [ycwu1997/SS-Net#2]
Traceback (most recent call last):
  File "/root/autodl-tmp/code/train_ss_3d.py", line 223, in <module>
    prototype_memory.add_features_from_sample_learned(model, proj_labeled_features_correct, labels_correct)
  File "/root/autodl-tmp/code/utils/feature_memory.py", line 36, in add_features_from_sample_learned
    selector = model.__getattr__('contrastive_class_selector_' + str(c))  # get the self attention moduel for class c
  File "/root/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1695, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'VNet' object has no attribute 'contrastive_class_selector_2'

**Comment by ycwu1997** [comment]
pls make sure the " for class_c in range(2):" lines 259/268 of https://github.com/ycwu1997/SS-Net/blob/main/code/networks/VNet.py. The num_classes is your denoted number of classes.
